#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*              Anil Madhavapeddy, OCaml Labs                             *
#*                                                                        *
#*   Copyright 2014 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

sudo: false

git:
  submodules: false

language: node_js
node_js:
  - "10.13.0"

matrix:
  include:

    # Default build
  - language: c
    script: bash -ex .travis-ci.sh
    env: CI_KIND=build XARCH=i386
    addons:
      apt:
        packages:
        - gcc:i386
        - cpp:i386
        - binutils:i386
        - binutils-dev:i386
        - libx11-dev:i386
        - libc6-dev:i386
    env: CI_KIND=build XARCH=x64
    env: CI_KIND=build XARCH=x64 CONFIG_ARG=-flambda OCAMLRUNPARAM=b,v=0
    env: CI_KIND=changes
    env: CI_KIND=tests

    allow_failures:
    - env: CI_KIND=tests

    # Esy builds
  - os: osx
    env: ESY_BUILD=YES ESY__CACHE=/home/travis/.esy
  - os: linux
    env: ESY_BUILD=YES ESY__CACHE=/home/travis/.esy

addons:
  apt:
    packages:
    - binutils-dev

notifications:
  email:
    - ocaml-ci-notifications@inria.fr

cache:
  directories:
  - $HOME/travis/.esy
  - $HOME/travis/.nvm
  - ./_build/default

install:
  - "if [[ $ESY_BUILD ]]; then npm --globall install esy@next; fi"

script: """
  if [[ $ESY_BUILD ]];
  then esy install && esy build;
  else ./.travis-ci.sh;
  fi
  """
